# Change these first
owner: jfcatano # Your GitHub organization or username, where this repository lives
repo: disruptive-uptime # The name of this repository

sites:
  - name: Disruptive Website
    url: https://www.disruptiveinfotech.com
  - name: Liga Antioqueña de Rugby - API
    url: https://apilarproject.disruptiveinfotech.com/
  - name: Liga Antioqueña de Rugby - Website
    url: https://lar.disruptiveinfotech.com/
  - name: Mesadoko - API
    url: https://apimesadoko.disruptiveinfotech.com/api/users
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.disrtuptiveinfotech.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**DisruptiveIT**, creando soluciones tecnológicas eficientes para todos los sistemas."
  introMessage: Aquí puedes ver el estado de todos los servicios activos y administrados por **Disruptive Information Tecnologies**. ¿Deseas conocer más sobre nuestros servicios? [**¡Ingresa a nuestra página web!**](https://disruptiveinfotech.com)
  navbar:
    - title: Servicios
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Página web
      href: https://disruptiveinfotech.com
    - title: LAR
      href: https://lar.disruptiveinfotech.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
